POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3Mzk5NDMwMjUsInVzZXJJZCI6MX0.ZY6-0WrMzZONaW3lb7clRBxMWPhENH0RtE2xFw--NVQ

{
	"name": "Test Event",
	"description": "Description",     
	"location": "Location",
	"dateTime": "2021-01-01T00:00:00Z"
}

