POST http://localhost:8080/students
content-type: application/json

{
    "name": "John Johnson",
    "university": "MIT",
    "department": "Mechanical Engineering",
    "age": 23,
    "address": {
      "street": "789 Oak St",
      "city": "Cambridge",
      "state": "MA",
      "zip": "02139"
    }
} 