DELETE http://localhost:8080/events/4
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QuY29tIiwiZXhwIjoxNzM5ODc4MjE0LCJ1c2VySWQiOjJ9.Ad13U98DF6Ogte2TaVXDL-8kGZx2LUmekHBLyTPw_LY