DELETE http://localhost:8080/events/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QuY29tIiwiZXhwIjoxNzM5OTQwOTMyLCJ1c2VySWQiOjJ9.4qzBsz2OCeqsLSSYH0AiqXAj3CQ4hzo3YByzcfFXLWA