PUT http://localhost:8080/events/3
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQHRlc3QuY29tIiwiZXhwIjoxNzM5OTQwMzgwLCJ1c2VySWQiOjJ9.OWV22SFrmrIfGeqi8rrw2DCdfgu0-1aTPFmjnPTXEOc

{
	"name": "Test Event new",
	"description": "Description new",     
	"location": "Location new",
	"dateTime": "2021-01-01T00:00:00Z"
}